# Generated by Django 3.2 on 2023-04-09 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_docu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidocu',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_docus', to=settings.AUTH_USER_MODEL),
        ),
    ]
