# Generated by Django 3.2 on 2023-02-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillForFrameWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skil_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'SkillForFrameWork',
            },
        ),
    ]
