# Generated by Django 3.2 on 2023-02-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_skillforframework'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skill_for_frameWork',
            field=models.ManyToManyField(related_name='skill_for_frameWorks', to='users.SkillForFrameWork'),
        ),
    ]
