# Generated by Django 3.2 on 2023-03-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='postion',
            field=models.CharField(default='', max_length=150),
        ),
    ]
