# Generated by Django 3.2 on 2023-03-01 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_postion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='postion',
            new_name='position',
        ),
    ]
