# Generated by Django 3.2 on 2023-03-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userposition',
            options={'verbose_name_plural': 'UserPosition'},
        ),
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
    ]
