# Generated by Django 3.2 on 2023-03-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_admin_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skill_for_frameWork',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='users.SkillForFrameWork'),
        ),
    ]
