# Generated by Django 3.2 on 2023-03-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_skill_for_framework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('frontend', 'FrontEnd'), ('backend', 'BackEnd')], max_length=20, null=True),
        ),
    ]
