# Generated by Django 3.2 on 2023-04-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cash',
            field=models.IntegerField(default=0),
        ),
    ]
