# Generated by Django 3.2 on 2023-04-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_edit_mode_for_study_note_contents',
            field=models.BooleanField(default=False),
        ),
    ]
