# Generated by Django 3.2 on 2023-05-16 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_usertaskcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_edit_mode_for_study_note_contents',
        ),
    ]
