# Generated by Django 3.2 on 2023-05-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_user_is_edit_mode_for_study_note_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertaskcomment',
            name='is_edit_mode',
        ),
        migrations.AddField(
            model_name='user',
            name='is_edit_mode_for_study_note_contents',
            field=models.BooleanField(default=False),
        ),
    ]
