# Generated by Django 3.2 on 2023-05-16 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20230516_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskcomment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_task_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertaskcomment',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
