# Generated by Django 3.2 on 2023-06-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20230516_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_note_url1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='study_note_url2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
