databases:
  - name: scgs_backend
    databaseName: scgs_backend
    user: scgs_backend
    region: singapore

services:
  - type: web
    name: scgs_backend
    env: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: scgs_backend
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4