# Generated by Django 3.2 on 2023-05-06 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='미정', max_length=30)),
                ('description', models.CharField(default='미정', max_length=50)),
                ('category', models.CharField(choices=[('month', '한 달 이상'), ('week', '일주일 이상'), ('day', '하루 이상')], default='month', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='long_term_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
