# Generated by Django 3.2 on 2023-05-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_maker', '0002_alter_longtermplan_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermplan',
            name='category',
            field=models.CharField(choices=[('project', 'project 일정'), ('study', 'study 일정'), ('event', 'event 일정')], default='project', max_length=10),
        ),
    ]
