# Generated by Django 3.2 on 2023-05-08 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_maker', '0003_alter_longtermplan_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermPlanContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('progress', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('hideChildren', models.BooleanField(default=False)),
                ('displayOrder', models.IntegerField()),
                ('dependencies', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='plan_maker.longtermplancontents')),
            ],
        ),
    ]
