# Generated by Django 3.2 on 2023-05-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_maker', '0005_alter_longtermplancontents_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermplancontents',
            name='type',
            field=models.CharField(choices=[('project', 'Project'), ('task', 'Task'), ('milestone', 'Milestone')], default='task', max_length=20),
        ),
    ]
