# Generated by Django 3.2 on 2023-05-09 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_maker', '0007_longtermplancontents_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longtermplancontents',
            name='plan',
        ),
        migrations.AddField(
            model_name='longtermplancontents',
            name='long_term_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='plan_maker.longtermplan'),
        ),
    ]
