# Generated by Django 3.2 on 2023-05-10 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_maker', '0008_auto_20230509_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longtermplancontents',
            name='hideChildren',
        ),
        migrations.RemoveField(
            model_name='longtermplancontents',
            name='project',
        ),
        migrations.RemoveField(
            model_name='longtermplancontents',
            name='type',
        ),
    ]
