# Generated by Django 4.0.9 on 2023-02-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=180)),
                ('product', models.CharField(default='', max_length=50)),
                ('manager', models.CharField(default='', max_length=80)),
                ('email', models.CharField(default='', max_length=80)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('content', models.TextField(default=True)),
                ('estimate_require_completion', models.CharField(choices=[('complete', '완료'), ('uncomplete', '비완료')], max_length=20)),
                ('memo', models.TextField(default=True)),
            ],
        ),
    ]
