# Generated by Django 4.0.9 on 2023-02-21 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Estimate',
        ),
    ]
