# Generated by Django 3.2 on 2023-04-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_note', '0003_studynotecontent_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='studynotecontent',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
