# Generated by Django 3.2 on 2023-06-11 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_note', '0004_studynotecontent_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studynote',
            options={'ordering': ['-id']},
        ),
    ]
