# Generated by Django 3.2 on 2023-06-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_note', '0006_cowriterforstudynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='studynotecontent',
            name='ref_url1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studynotecontent',
            name='ref_url2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studynotecontent',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
