# Generated by Django 3.2 on 2023-06-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_note', '0007_auto_20230616_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='studynotecontent',
            name='task_classification',
            field=models.CharField(choices=[('subtitle_for_page ', '페이지 서브 타이틀'), ('note_content', '노트 내용'), ('youtube', 'youtube content')], default='note_content', max_length=20),
        ),
    ]
