# Generated by Django 3.2 on 2023-06-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_note', '0008_studynotecontent_task_classification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studynotecontent',
            old_name='task_classification',
            new_name='content_option',
        ),
    ]
