# Generated by Django 3.2 on 2023-06-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_note', '0011_auto_20230618_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studynote',
            name='first_category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend')], default='frontend', max_length=20),
        ),
    ]
