# Generated by Django 3.2 on 2023-06-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_note', '0013_classroomforstudynote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomforstudynote',
            name='current_page',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
