# Generated by Django 3.2 on 2023-06-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_note', '0018_errorreportforstudynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorreportforstudynote',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorreportforstudynote',
            name='page',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
