# Generated by Django 3.2 on 2023-08-26 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_note', '0019_auto_20230625_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studynotecontent',
            name='content_option',
            field=models.TextField(choices=[('subtitle_for_page ', '페이지 서브 타이틀'), ('note_content', '노트 내용'), ('youtube', 'youtube content')], default='note_content', max_length=20),
        ),
        migrations.CreateModel(
            name='FAQBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('page', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('study_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_list', to='study_note.studynote')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
