# Generated by Django 3.2 on 2023-11-01 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_note', '0030_roadmapcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmap',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='commentforerrorreport',
            name='error_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_report_list', to='study_note.errorreportforstudynote'),
        ),
    ]
