# Generated by Django 3.2 on 2023-11-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_note', '0035_rename_liked_at_bookmarkforstudynote_bookmarked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studynote',
            name='description',
            field=models.TextField(blank=True, default='black', null=True),
        ),
    ]
