# Generated by Django 3.2 on 2023-11-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_note', '0036_alter_studynote_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studynote',
            name='description',
            field=models.TextField(default='black'),
        ),
    ]
