# Generated by Django 3.2 on 2023-12-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_note', '0038_alter_studynote_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studynote',
            name='first_category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('full_stack', 'FullStack')], default='frontend', max_length=20),
        ),
        migrations.AlterField(
            model_name='studynote',
            name='title',
            field=models.CharField(default='black', max_length=80),
        ),
    ]
