# Generated by Django 3.2 on 2023-03-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='', max_length=50)),
                ('writer', models.CharField(default='', max_length=80)),
                ('importance', models.CharField(default='', max_length=80)),
                ('task_status', models.CharField(choices=[('proceeding', '진행'), ('uncomplete', '비완료'), ('complete', '완료')], max_length=20)),
                ('password', models.TextField(default=True)),
            ],
        ),
    ]
