# Generated by Django 3.2 on 2023-03-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogress',
            name='password',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
