# Generated by Django 3.2 on 2023-03-20 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_progress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectprogress',
            name='task_status',
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='started_at_utc',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='task_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='task_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progect_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='importance',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='password',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='writer',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
