# Generated by Django 3.2 on 2023-03-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0002_alter_projectprogress_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogress',
            name='task_status',
            field=models.CharField(choices=[('request', '요청'), ('proceeding', '진행'), ('uncomplete', '비완료'), ('complete', '완료')], max_length=20),
        ),
    ]
