# Generated by Django 3.2 on 2023-03-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0003_alter_projectprogress_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogress',
            name='task_status',
            field=models.CharField(choices=[('uncomplete', '비완료'), ('complete', '완료')], max_length=20),
        ),
    ]
