# Generated by Django 3.2 on 2023-03-09 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0004_alter_projectprogress_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogress',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='importance',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
