# Generated by Django 3.2 on 2023-03-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0004_auto_20230323_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogress',
            name='is_testing',
            field=models.BooleanField(default=False),
        ),
    ]
