# Generated by Django 3.2 on 2023-03-26 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_progress', '0005_projectprogress_is_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementaryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(blank=True, default='', null=True)),
                ('task_status', models.CharField(blank=True, choices=[('ready', '대기'), ('in_progress', '준비'), ('testing', '테스트중'), ('completed', '완료')], max_length=20, null=True)),
                ('importance', models.IntegerField(blank=True, default=1, null=True)),
                ('password', models.CharField(default=True, max_length=20)),
                ('started_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('task_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_manager_for_supplementary_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
