# Generated by Django 3.2 on 2023-03-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0005_auto_20230309_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogress',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
