# Generated by Django 3.2 on 2023-03-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0006_supplementarytask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementarytask',
            name='task_status',
            field=models.CharField(choices=[('ready', '대기'), ('in_progress', '준비'), ('testing', '테스트중'), ('completed', '완료')], default='ready', max_length=20),
        ),
    ]
