# Generated by Django 3.2 on 2023-03-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0007_alter_supplementarytask_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementarytask',
            name='task_status',
            field=models.CharField(choices=[('ready', '준비'), ('in_progress', '작업중'), ('testing', '테스트중'), ('completed', '완료')], default='ready', max_length=20),
        ),
    ]
