# Generated by Django 3.2 on 2023-03-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0008_alter_supplementarytask_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementarytask',
            name='password',
            field=models.CharField(default='1234', max_length=20),
        ),
    ]
