# Generated by Django 3.2 on 2023-03-26 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0009_alter_supplementarytask_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementarytask',
            name='orginal_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_tasks', to='project_progress.projectprogress'),
        ),
    ]
