# Generated by Django 3.2 on 2023-03-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0010_rename_task_status_projectprogress_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogress',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
