# Generated by Django 3.2 on 2023-03-19 00:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0011_projectprogress_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogress',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
