# Generated by Django 3.2 on 2023-03-27 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0011_rename_supplementarytask_extratask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extratask',
            old_name='orginal_task',
            new_name='original_task',
        ),
    ]
