# Generated by Django 3.2 on 2023-03-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0012_alter_projectprogress_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
