# Generated by Django 3.2 on 2023-03-20 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_progress', '0013_alter_projectprogress_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogress',
            name='task_manager',
            field=models.ForeignKey(default=94, on_delete=django.db.models.deletion.CASCADE, related_name='progect_tasks', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='writer',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
