# Generated by Django 3.2 on 2023-03-28 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0013_projectprogress_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestForTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_description', models.CharField(default='', max_length=50)),
                ('test_status', models.BooleanField(default=False)),
                ('original_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_for_tasks', to='project_progress.projectprogress')),
            ],
        ),
    ]
