# Generated by Django 3.2 on 2023-03-20 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_progress', '0014_auto_20230320_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogress',
            name='task_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progect_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
