# Generated by Django 3.2 on 2023-03-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0015_alter_testfortask_original_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfortask',
            name='task_method',
            field=models.CharField(choices=[('browser', '브라우져'), ('postman', 'postman'), ('test_code', 'test_code')], default='browser', max_length=20),
        ),
        migrations.AddField(
            model_name='testfortask',
            name='test_result_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
