# Generated by Django 3.2 on 2023-03-28 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0016_auto_20230329_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testfortask',
            old_name='task_method',
            new_name='test_method',
        ),
    ]
