# Generated by Django 3.2 on 2023-04-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0019_testersfortest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testersfortest',
            old_name='task',
            new_name='test',
        ),
    ]
