# Generated by Django 3.2 on 2023-04-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0023_taskcomment_is_edit_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogress',
            name='task',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='writer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
