# Generated by Django 3.2 on 2023-04-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0024_auto_20230412_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogress',
            name='current_status',
            field=models.CharField(choices=[('ready', '준비'), ('in_progress', '작업중'), ('testing', '테스트중'), ('completed', '완료')], default='ready', max_length=20),
        ),
    ]
