# Generated by Django 3.2 on 2023-04-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0026_projectprogress_check_result_by_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogress',
            name='score_by_tester',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
