# Generated by Django 3.2 on 2023-04-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0029_auto_20230420_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogress',
            name='cash_prize',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='is_urgent_request',
            field=models.BooleanField(default=False),
        ),
    ]
