# Generated by Django 3.2 on 2023-04-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0034_alter_challengersforcashprize_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogress',
            name='check_for_cash_prize',
            field=models.BooleanField(default=False),
        ),
    ]
