# Generated by Django 3.2 on 2023-05-05 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0036_projectprogress_is_for_urgent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectprogress',
            old_name='is_for_urgent',
            new_name='is_task_for_urgent',
        ),
    ]
