# Generated by Django 3.2 on 2023-05-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0039_projectprogress_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectprogress',
            name='order',
        ),
    ]
