# Generated by Django 3.2 on 2023-05-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0043_tasklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='taskPk',
            field=models.IntegerField(default=0),
        ),
    ]
