# Generated by Django 3.2 on 2023-05-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0044_tasklog_taskpk'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='time_distance_for_my_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='time_distance_for_team_task',
            field=models.IntegerField(default=0),
        ),
    ]
