# Generated by Django 3.2 on 2023-05-24 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0045_auto_20230524_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='original_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='project_progress.projectprogress'),
        ),
    ]
