# Generated by Django 3.2 on 2023-05-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0046_tasklog_original_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='completed_at_formatted',
            field=models.CharField(default='', max_length=30),
        ),
    ]
