# Generated by Django 3.2 on 2023-05-24 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0047_tasklog_completed_at_formatted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklog',
            name='completed_at_formatted',
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
