# Generated by Django 3.2 on 2023-05-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0049_tasklog_completed_at_formatted'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogress',
            name='task_url1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='task_url2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
