# Generated by Django 3.2 on 2023-05-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0050_auto_20230529_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='extratask',
            name='task_url1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extratask',
            name='task_url2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
