# Generated by Django 3.2 on 2023-05-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0051_auto_20230530_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extratask',
            name='task_url1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extratask',
            name='task_url2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
