# Generated by Django 3.2 on 2023-06-02 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0057_extrataskcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestForExtraTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests_for_extra_task', to='project_progress.extratask')),
            ],
        ),
    ]
