# Generated by Django 3.2 on 2023-06-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0058_testforextratask'),
    ]

    operations = [
        migrations.AddField(
            model_name='testforextratask',
            name='test_description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='testforextratask',
            name='test_method',
            field=models.CharField(choices=[('browser', '브라우져'), ('postman', 'postman'), ('test_code', 'test_code')], default='browser', max_length=20),
        ),
        migrations.AddField(
            model_name='testforextratask',
            name='test_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testforextratask',
            name='test_result_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
