# Generated by Django 3.2 on 2023-06-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0060_testersfortestforextratask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestersForTestForExtraTask',
        ),
    ]
