# Generated by Django 3.2 on 2023-07-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0065_alter_projectprogress_due_date_option_for_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogress',
            name='is_for_today',
            field=models.BooleanField(default=False),
        ),
    ]
