# Generated by Django 3.2 on 2023-10-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0067_remove_projectprogress_is_for_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='extratask',
            name='task_description',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
    ]
