# Generated by Django 3.2 on 2023-10-13 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0069_extramanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testfortask',
            name='original_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests_for_task', to='project_progress.projectprogress'),
        ),
    ]
