# Generated by Django 3.2 on 2023-04-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_note', '0003_technotecontent_tech_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technotecontent',
            old_name='content',
            new_name='note_content_content',
        ),
        migrations.RenameField(
            model_name='technotecontent',
            old_name='file',
            new_name='note_content_file',
        ),
        migrations.RenameField(
            model_name='technotecontent',
            old_name='title',
            new_name='note_content_title',
        ),
    ]
