# Generated by Django 3.2 on 2023-04-04 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0018_rename_test_status_testfortask_test_passed'),
        ('tech_note', '0005_technotetester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technotetester',
            name='tech_note',
        ),
        migrations.AddField(
            model_name='technotetester',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testers_for_task', to='project_progress.projectprogress'),
        ),
    ]
