# Generated by Django 3.2 on 2023-04-04 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_note', '0006_auto_20230404_1405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechNoteTester',
        ),
    ]
