# Generated by Django 3.2 on 2023-04-13 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_progress', '0024_auto_20230412_0707'),
        ('tech_note', '0007_delete_technotetester'),
    ]

    operations = [
        migrations.AddField(
            model_name='technote',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_notes', to='project_progress.projectprogress'),
        ),
    ]
