# Generated by Django 3.2 on 2023-10-30 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_note', '0009_loadmap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoadMap',
        ),
    ]
