# Generated by Django 3.2 on 2023-03-20 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0007_rename_image_url_referimagefortask_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referimagefortask',
            old_name='image_file',
            new_name='image_url',
        ),
    ]
