# Generated by Django 3.2 on 2023-04-07 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0009_testresultimagefortask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresultimagefortask',
            old_name='task',
            new_name='test',
        ),
    ]
