# Generated by Django 3.2 on 2023-04-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='shortcut',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
