# Generated by Django 3.2 on 2023-04-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcut', '0004_alter_shortcut_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='shortcut',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
