# Generated by Django 3.2 on 2023-11-06 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcut', '0010_shortcuthub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortcuthub',
            old_name='name',
            new_name='title',
        ),
    ]
