# Generated by Django 3.2 on 2023-11-06 23:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortcut', '0011_rename_name_shortcuthub_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortcutHub',
            new_name='ShortCutHub2',
        ),
    ]
