# Generated by Django 3.2 on 2023-03-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=180)),
                ('description', models.CharField(default='', max_length=50)),
                ('teacher', models.CharField(default='', max_length=80)),
                ('open_chat_url', models.URLField(blank=True, null=True)),
                ('framework_option', models.CharField(blank=True, choices=[('django_drf', 'django_drf'), ('fast_api', 'fast_api'), ('sptring_boot', 'spring_boot'), ('nest_js', 'nest_js'), ('flutter', 'flutter')], max_length=20, null=True)),
            ],
        ),
    ]
