# Generated by Django 3.2 on 2023-03-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
