# Generated by Django 3.2 on 2023-03-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorial_tutorial_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='framework_option',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='backend_framework_option',
            field=models.CharField(blank=True, choices=[('django_drf', 'django_drf'), ('fast_api', 'fast_api'), ('sptring_boot', 'spring_boot'), ('express', 'express'), ('nest_js', 'nest_js')], max_length=20, null=True),
        ),
    ]
