# Generated by Django 3.2 on 2023-03-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_alter_tutorial_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
