# Generated by Django 3.2 on 2023-03-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_auto_20230304_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='teacher',
            field=models.CharField(default='', max_length=25),
        ),
    ]
