# Generated by Django 3.2 on 2023-03-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_tutorial_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='frontend_framework_option',
            field=models.CharField(blank=True, choices=[('django_drf', 'django_drf'), ('fast_api', 'fast_api'), ('sptring_boot', 'spring_boot')], max_length=20, null=True),
        ),
    ]
