# Generated by Django 3.2 on 2023-03-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_alter_tutorial_frontend_framework_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='frontend_framework_option',
            field=models.CharField(blank=True, choices=[('react', 'react'), ('svelte', 'svelte'), ('flutter', 'flutter')], max_length=20, null=True),
        ),
    ]
