# Generated by Django 3.2 on 2023-03-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0010_tutorial_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='unlike_count',
            field=models.IntegerField(default=0),
        ),
    ]
