# Generated by Django 3.2 on 2023-09-14 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='category',
            new_name='subtitle',
        ),
    ]
