# Generated by Django 3.2 on 2023-09-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_rename_category_challenge_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='main_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
