# Generated by Django 3.2 on 2023-09-16 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0003_challenge_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], default='Pass', max_length=20)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
            ],
        ),
        migrations.RemoveField(
            model_name='challenger',
            name='challenge_scores',
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_criterials', to='challenges.challenge'),
        ),
        migrations.DeleteModel(
            name='ScoreForChallenge',
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.evaluationcriteria'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenger',
            name='evaluation_results',
            field=models.ManyToManyField(related_name='challengers', to='challenges.EvaluationResult'),
        ),
    ]
