# Generated by Django 3.2 on 2023-09-16 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0006_auto_20230916_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenger',
            old_name='participant',
            new_name='challenger',
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='challenger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='criteria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='challenges.evaluationcriteria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='evaluator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenger',
            name='evaluation_results',
            field=models.ManyToManyField(related_name='challenger_results', to='challenges.EvaluationResult'),
        ),
        migrations.AlterField(
            model_name='evaluationresult',
            name='result',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Undecided', 'Undecided')], default='Pass', max_length=20),
        ),
    ]
