# Generated by Django 3.2 on 2023-09-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_auto_20230916_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenger',
            old_name='challenger',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='evaluationresult',
            old_name='criteria',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='challenger',
            name='evaluation_results',
        ),
        migrations.RemoveField(
            model_name='evaluationresult',
            name='evaluator',
        ),
    ]
