# Generated by Django 3.2 on 2023-09-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_auto_20230918_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='item_description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='evaluationresult',
            name='evaluate_criteria_description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
