# Generated by Django 3.2 on 2023-09-18 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_auto_20230918_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationresult',
            name='challenge',
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='challenge',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='challenges.challenge'),
            preserve_default=False,
        ),
    ]
