# Generated by Django 3.2 on 2023-09-18 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_auto_20230918_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationresult',
            old_name='user',
            new_name='challenger',
        ),
    ]
