# Generated by Django 3.2 on 2023-09-23 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0013_auto_20230923_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
