# Generated by Django 3.2 on 2023-09-23 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0014_auto_20230923_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_status', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='challenges.challenge')),
            ],
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='challenge_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_result', to='challenges.challengeresult'),
        ),
    ]
