# Generated by Django 3.2 on 2023-09-23 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0016_remove_evaluationresult_challenge_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeresult',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_results', to='challenges.challenge'),
        ),
    ]
