# Generated by Django 3.2 on 2023-09-25 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0019_auto_20230924_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_classfication', models.CharField(choices=[('commenter', 'Commenter'), ('challenger', 'Challenger'), ('participant', 'Participant')], default=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL), max_length=20)),
                ('comment', models.TextField()),
                ('commenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
