# Generated by Django 3.2 on 2023-09-25 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0020_challengecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengecomment',
            name='challenge',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_comments', to='challenges.challenge'),
            preserve_default=False,
        ),
    ]
