# Generated by Django 3.2 on 2023-09-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0024_auto_20230925_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengecomment',
            name='commenter_classfication',
        ),
        migrations.AddField(
            model_name='challengecomment',
            name='writer_classfication',
            field=models.CharField(choices=[('commenter', 'Commenter'), ('challenger', 'Challenger'), ('participant', 'Participant')], default='commenter', max_length=20),
        ),
    ]
