# Generated by Django 3.2 on 2023-09-26 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0027_auto_20230927_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_criterials', to='challenges.challenge'),
        ),
    ]
