# Generated by Django 3.2 on 2023-09-28 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0029_alter_challengerref_challenge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengeresult',
            old_name='note_url',
            new_name='note_url1',
        ),
        migrations.AlterField(
            model_name='challengerref',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenger_ref', to='challenges.challenge'),
        ),
    ]
