# Generated by Django 3.2 on 2023-09-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_survey_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyoption',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_options', to='survey.survey'),
        ),
    ]
