# Generated by Django 3.2 on 2023-09-20 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20230920_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyanswer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', to='survey.survey'),
        ),
    ]
